### ISSUE TITLE
CI: make and GitHub actions..

### ISSUE THREAD

**Issue by gedw99** [dawenxi-tech/2fa#7]
Hey @heramerom 

let’s me know if you want help with this …

Apple first of course .

Aspects:

Signing . Notary 
Store creation via Apple Urls. Make it easy.
Uploading . make it easy.
Assets. All the stuff you must create like screen shots for App Store. Gioui has a Screenshot  util we can automate.

**Comment by gedw99** [comment]
Github actions can call the makefile reducing the amount of GitHub actions code and complexity and so make it easier to do windows and Linux layer too.

**Comment by heramerom** [comment]
Thank you for help. Yes I will write Github actions and make release easier, but I have to focuse on develop features develop right now. 
I wan to make a tray on system status bar but breaking with some problem now. It seems that I have to fork the Gio and add some features.
If with your help on Github actions it will easier and much helpful.

And I will not publish on App Store, due to I have no app store account.

**Comment by gedw99** [comment]
Sure. I can do the GitHub actins as PR it

For sys tray here's an idea
https://github.com/0xfederama/water-reminder gets you the menu

https://github.com/gioui-plugins/gio-plugins/tree/main/webviewer gets you the GUI as a Webview. Whatever GUi you want can be written in gio and compiled to WASM and run inside the web view.

I know its a round about way to do it but might work.

**Comment by heramerom** [comment]
Thank you. The gio-plugins is amazing, I will have a try, hope it works for me.

**Comment by gedw99** [comment]
What is are you on ?

I am on Mac arm and windows arm.
There is a minor issue on windows arm that I will work out with the maintainer.

it works on mobiles btw

**Comment by heramerom** [comment]
I am on Mac amd64 and Windows x64.

**Comment by gedw99** [comment]
Perfect then. I will Test arm.

i will try to finish the GitHub actions
